// Site configuration — generated by the Accounting Prework setup tool
// Place this file in the root of your prework site folder.

const SITE_CONFIG = {
  "institution": "Yale School of Management",
  "courseTitle": "Accounting Pre-Work",
  "instructor": {
    "name": "Rick Antle",
    "title": "William S. Beinecke Professor of Accounting"
  },
  "colors": {
    "primary": "#00329d",
    "primaryLight": "#286dc0",
    "accent": "#bd5319",
    "faint": "#f0f4f8"
  },
  "logo": {
    "type": "letter",
    "value": "Y"
  },
  "mascot": null,
  "welcomeText": null,
  "modules": [1, 2, 3, 4, 5, 6, 7, 8],
  "audience": "mixed"
};
